# Generated by Django 5.1.7 on 2025-06-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('USUARIO', 'Usuário'), ('ADMIN ', 'Admin')], max_length=10),
        ),
    ]
