# Generated by Django 5.1.7 on 2025-06-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('USUARIO', 'Usuário'), ('ADMIN', 'Administrador')], max_length=10),
        ),
    ]
