# Generated by Django 5.1.7 on 2025-06-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_smtp_host',
            field=models.CharField(default='smtp.gmail.com', help_text='Servidor SMTP (ex: smtp.gmail.com)', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_smtp_password',
            field=models.CharField(blank=True, help_text='Senha de app do Gmail ou senha do email para SMTP', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_smtp_port',
            field=models.IntegerField(default=587, help_text='Porta SMTP (ex: 587 para TLS, 465 para SSL)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_use_tls',
            field=models.BooleanField(default=True, help_text='Usar TLS para conexão segura'),
        ),
    ]
