# Generated by Django 5.1.7 on 2025-06-15 22:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearvault', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterModelOptions(
            name='itemcompra',
            options={'managed': True, 'verbose_name': 'Item da Compra', 'verbose_name_plural': 'Itens da Compra'},
        ),
        migrations.AlterUniqueTogether(
            name='estoque',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='compra',
            name='status',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='valor_total',
        ),
        migrations.RemoveField(
            model_name='comprador',
            name='departamento',
        ),
        migrations.AddField(
            model_name='estoque',
            name='lote',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estoque', to='gearvault.loteestoque'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.MinLengthValidator(14), django.core.validators.MaxLengthValidator(14)]),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gearvault.endereco'),
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='produto',
        ),
    ]
