# Generated by Django 5.1.7 on 2025-06-15 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gearvault', '0002_endereco_alter_itemcompra_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='quantidade',
        ),
    ]
