# Generated by Django 5.1.7 on 2025-06-15 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearvault', '0003_remove_estoque_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(default=1, max_length=14, validators=[django.core.validators.MinLengthValidator(14), django.core.validators.MaxLengthValidator(14)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(default=1, max_length=11, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11)]),
            preserve_default=False,
        ),
    ]
