# Generated by Django 5.1.7 on 2025-06-15 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearvault', '0004_alter_fornecedor_cnpj_alter_fornecedor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gearvault.endereco'),
        ),
    ]
