# Generated by Django 5.1.7 on 2025-06-17 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearvault', '0005_alter_fornecedor_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='local',
        ),
        migrations.AddField(
            model_name='compra',
            name='estoque',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='gearvault.estoque'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estoque',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estoque',
            name='nome',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemcompra',
            name='local',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gearvault.localarmazenamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localarmazenamento',
            name='estoque',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='locais', to='gearvault.estoque'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LoteEstoque',
        ),
    ]
